---

- name: Update and upgrade apt packages
  apt:
    upgrade: true
    update_cache: true

- name: apt install the required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tmux
    - screen

- name: Remove useless packages from the cache
  apt:
    autoclean: true
    autoremove: true
