---

- name: Update and upgrade apt packages
  apt:
    upgrade: "full"
    update_cache: yes

- name: apt install the required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tmux
    - screen

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
    autoremove: yes
