---
- name: Update and upgrade apt packages
  apt:
    upgrade: full
    update_cache: yes

- name: Add ppa:ondrej/php repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: apt install the required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    # general tools
    - tmux
    - screen
    - vim
    - git
    # linux packages required by opencaching code
    - sendmail
    # php related packages
    - php8.1
    - php-apcu
    - php-common
    - php-pear
    - php-xml
    - php8.1
    - php8.1-apcu
    - php8.1-bz2
    - php8.1-cli
    - php8.1-common
    - php8.1-curl
    - php8.1-fpm
    - php8.1-gd
    - php8.1-imagick
    - php8.1-intl
    - php8.1-mbstring
    - php8.1-mysql
    - php8.1-opcache
    - php8.1-phpdbg
    - php8.1-readline
    - php8.1-xml
    - php8.1-zip
    # apache2
    - apache2
    - libapache2-mod-php8.1
    # database
    - phpmyadmin # this will install multiple other dependencies and other version of php that is installed previously. (todo) Consider installing phpmyadmin manually.
    - mariadb-server
    # required for deployment
    - python3-mysqldb
    - pv

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
    autoremove: yes
