---
- name: Copy mardiadb custom settings
  copy:
    src: files/database/99-local.cnf
    dest: /etc/mysql/mariadb.conf.d/99-local.cnf

- name: Copy mardiadb custom settings
  copy:
    src: files/database/ocpl.cnf
    dest: /etc/mysql/conf.d/ocpl.cnf

- name: Restart mariadb
  command: systemctl restart mariadb

- name: Wait for maridb
  pause:
    seconds: 5

- name: Is database root password set?
  command: mysql -u root --execute "SELECT NOW()"
  register: is_root_password_set
  ignore_errors: yes

- name: Delete anonymous users
  mysql_user:
    user=""
    state="absent"
  when: is_root_password_set.rc == 0

- name: Set root password
  mysql_user:
    user=root
    password="toor"
    host=localhost
  when: is_root_password_set.rc == 0

- name: Opencaching database already exists?
  command: mysql -u root -ptoor --execute "use ocpl;"
  register: is_ocpl_db_existing
  ignore_errors: yes

- name: Download OC devel database to /tmp/
  get_url:
    url: https://s3api.zylowski.net/public/ocpl_devel_dump-2018.sql.gz
    dest: /tmp/oc_devel_db.sql.gz
  when: is_ocpl_db_existing.rc != 0

- name: Create ocpl database
  command: mysql -u root -ptoor --execute "CREATE DATABASE ocpl;"
  when: is_ocpl_db_existing.rc != 0

- name: Import OC devel database
  shell: pv /tmp/oc_devel_db.sql.gz | gunzip | mysql -u root -ptoor ocpl
  when: is_ocpl_db_existing.rc != 0

- name: Delete devel dump
  file:
    state: absent
    path: /tmp/oc_devel_db.sql.gz

- name: Copy phpmyadmin config
  command: ln -s /etc/phpmyadmin/apache.conf /etc/apache2/conf-available/phpmyadmin.conf
  ignore_errors: yes

- name: Enable phpmyadmin config
  command: a2enconf phpmyadmin

- name: Reload apache2
  command: systemctl reload apache2
