---
- name: Copy apache configuration for opencaching site
  copy:
    src: files/webserver/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf

- name: Copy apache configuration for mobile opencaching site
  copy:
    src: files/webserver/mobile.conf
    dest: /etc/apache2/sites-enabled/mobile.conf

- name: Adjust ownership for apache logs directory
  file:
    path: /var/log/apache2
    owner: user
    group: adm
    recurse: yes

- name: Clone opencaching repo master branch
  git:
    repo: https://github.com/opencaching/opencaching-pl.git
    dest: /srv/ocpl

- name: Prevent fatal errors during running php evel git commands in /srv/ocpl
  command: git config --system --add safe.directory /srv/ocpl

- name: Adjust ownership for /srv/ocpl
  file:
    path: /srv/ocpl
    owner: user
    group: www-data
    recurse: yes

- name: Create /srv/ocpl-dynamic-files
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: root
  loop:
    - /srv/ocpl-dynamic-files/images/mini-mapa
    - /srv/ocpl-dynamic-files/images/statpics
    - /srv/ocpl-dynamic-files/images/uploads
    - /srv/ocpl-dynamic-files/mp3
    - /srv/ocpl-dynamic-files/searchdata
    - /srv/ocpl-dynamic-files/tmp
    - /srv/ocpl-dynamic-files/tpl
    - /srv/ocpl-dynamic-files/wigo
    - /srv/ocpl-dynamic-files/download/zip

- name: Copy oc node configuration file
  copy:
    src: files/ocpl/settings.inc.php
    dest: /srv/ocpl/lib/settings.inc.php

- name: Enable rewrite module
  apache2_module:
    name: rewrite
    state: present

- name: Copy FPM custom settings
  copy:
    src: files/php/fpm/99-local.ini
    dest: /etc/php/8.1/fpm/conf.d/99-local.ini

- name: Restart services
  command: systemctl restart "{{ item }}"
  loop:
    - apache2
    - php8.1-fpm
